meta:
  # copied from https://github.com/cloudfoundry/cf-release/blob/master/templates/cf-jobs.yml#L15
  nfs_client_ranges:
    - (( .networks.cf1.subnets.[0].range || nil ))

  nfs_server:
    address: (( merge || jobs.nfs_z1.networks.cf1.static_ips.[0] || nil ))
    allow_from_entries: (( merge || meta.nfs_client_ranges ))

properties:
  nfs_server:
    share_path: /var/vcap/store
  template_only:
    aws:
      <<: (( merge ))
      access_key_id: ~
      secret_access_key: ~
  cc:
    resource_pool:
      fog_connection: ~
    packages:
      fog_connection: ~
    droplets:
      fog_connection: ~
    buildpacks:
      fog_connection: ~

networks: (( merge ))

jobs:
  - <<: (( merge ))
  - name: nfs_z1
    instances: 1
    networks:
      - name: cf1
        static_ips: (( static_ips(3) ))
    properties:
      <<: (( merge ))
      nfs_server: (( meta.nfs_server ))

